## `persp()`

```{r persp-a, echo = FALSE, fig.height = 5.8, fig.width = 9}
y <- x <- seq(-10, 10, length.out = 50)

rotsinc <- function(x,y){
  sinc <- function(x){y <- sin(x) / x ; y[is.na(y)] <- 1; y}
  10 * sinc(sqrt(x^2 + y^2))
}

z <- outer(x, y, rotsinc)

par(mfrow = c(2, 2), mar = rep(0, 4))

persp(x, y, z, theta = 30, phi = 30, expand = 0.5, col = "lightblue")

persp(x, y, z, theta = 20, phi = 45, expand = 0.5, col = "lightblue",
      ltheta = 120, shade = 0.75, 
      xlab = "X", ylab = "Y", zlab = "Z")

persp(x, y, -z, theta = 30, phi = 30, expand = 0.5, col = "lightblue")

persp(x, y, -z, theta = 20, phi = 45, expand = 0.5, col = "lightblue",
      ltheta = 120, shade = 0.75, 
      xlab = "X", ylab = "Y", zlab = "Z")
```

## `persp()`

```{r persp-b, echo = FALSE, fig.height = 6, fig.width = 9}
par(mfrow = c(2,2), mar = rep(0, 4))
## (2) Visualizing a simple DEM model

z <- 2 * volcano        # Exaggerate the relief
x <- 10 * (1:nrow(z))   # 10 meter spacing (S to N)
y <- 10 * (1:ncol(z))   # 10 meter spacing (E to W)

persp(x, y, z, theta = 120, phi = 15, scale = FALSE, axes = FALSE)

z0 <- min(z) - 20
z <- rbind(z0, cbind(z0, z, z0), z0)
x <- c(min(x) - 1e-10, x, max(x) + 1e-10)
y <- c(min(y) - 1e-10, y, max(y) + 1e-10)
fill <- matrix("green3", nrow = nrow(z)-1, ncol = ncol(z)-1)
fill[ , i2 <- c(1,ncol(fill))] <- "gray"
fill[i1 <- c(1,nrow(fill)) , ] <- "gray"

persp(x, y, z, theta = 120, phi = 15, col = fill, scale = FALSE, axes = FALSE)

persp(x, y, z, theta = 135, phi = 30, col = "green3", scale = FALSE,
      ltheta = -120, shade = 0.75, border = NA, box = FALSE)

fcol <- fill ; fcol[] <- terrain.colors(nrow(fcol))
fcol <- fill

zi <- volcano[ -1,-1] + volcano[ -1,-61] +
  volcano[-87,-1] + volcano[-87,-61]  ## / 4

fcol[-i1,-i2] <- terrain.colors(20)[
  cut(zi,stats::quantile(zi, seq(0,1, length.out = 21)), include.lowest = TRUE)
  ]

persp(x, y, 2*z, theta = 110, phi = 40, col = fcol, scale = FALSE,
      ltheta = -120, shade = 0.4, border = NA, box = FALSE)
```

## `contour()`

```{r contour-a, echo = FALSE}
x <- -6:16
par(mfrow = c(2, 2), mar = rep(0, 4))

contour(outer(x, x), method = "edge", vfont = c("sans serif", "plain"))

z <- outer(x, sqrt(abs(x)), FUN = "/")

image(x, x, z)

contour(x, x, z, col = "pink", add = TRUE, method = "edge",
        vfont = c("sans serif", "plain"))

contour(x, x, z, ylim = c(1, 6), method = "simple", labcex = 1,
        xlab = quote(x[1]), ylab = quote(x[2]))

contour(x, x, z, ylim = c(-6, 6), nlev = 20, lty = 2, method = "simple")
```

##  `contour()`

```{r contour-b, echo = FALSE}
## Persian Rug Art:
par(mfrow = c(2, 2), mar = rep(0, 4))
x <- y <- seq(-4*pi, 4*pi, len = 27)
r <- sqrt(outer(x^2, y^2, "+"))

for(f in pi^(0:3))
  contour(cos(r^2)*exp(-r/f),
          drawlabels = FALSE, axes = FALSE, frame = TRUE)
```

## `image()`

```{r image, echo = FALSE, fig.height = 5.5, fig.width = 8}
par(mfrow = c(2, 2), mar = rep(0.5, 4))

x <- 10*(1:nrow(volcano)); x.at <- seq(100, 800, by=100)
y <- 10*(1:ncol(volcano)); y.at <- seq(100, 600, by=100)

image(x, y, volcano, col=terrain.colors(100),axes=FALSE)
contour(x, y, volcano, levels=seq(90, 200, by=5), add=TRUE, col="brown")

image(x, y, volcano, col=heat.colors(100), axes=FALSE)
contour(x, y, volcano, levels=seq(90, 200, by=5), add=TRUE, col="brown")

y <- x <- seq(-10, 10, length.out = 50)
z <- outer(x, y, rotsinc)

image(x, y, z, col=heat.colors(100), axes=FALSE)
contour(x, y, z, levels=seq(0, 50, by=1), add=TRUE, col="brown")

image(x, y, z, col=terrain.colors(100), axes=FALSE)
contour(x, y, z, levels=seq(0, 50, by=1), add=TRUE, col="brown")

```

## `symbols()`

```{r symbols, echo = FALSE, fig.height = 5, fig.width = 8}
x <- 1:10
y <- sort(10*runif(10))
z <- runif(10)
z3 <- cbind(z, 2*runif(10), runif(10))

par(mfrow = c(2,2), mar = rep(0, 4))

symbols(x, y, thermometers = cbind(.5, 1, z), inches = .5, fg = 1:10)
symbols(x, y, thermometers = z3, inches = FALSE)
text(x, y, apply(format(round(z3, digits = 2)), 1, paste, collapse = ","),
     adj = c(-.2,0), cex = .75, col = "purple", xpd = NA)

## Note that  example(trees)  shows more sensible plots!
N <- nrow(trees)
with(trees, {
  ## Girth is diameter in inches
  symbols(Height, Volume, circles = Girth/24, inches = FALSE)
  op <- palette(rainbow(N, end = 0.9))
  symbols(Height, Volume, circles = Girth/16, inches = FALSE, bg = 1:N,
          fg = "gray30")
  palette(op)
})
```

## `fourfoldplot()`

```{r fourfoldplot, echo = FALSE, fig.height = 5, fig.width = 8}
x <- aperm(UCBAdmissions, c(2, 1, 3))
dimnames(x)[[2]] <- c("Yes", "No")
names(dimnames(x)) <- c("Sex", "Admit?", "Department")

par(mfrow = c(1,2), mar = rep(0, 4))

fourfoldplot(margin.table(x, c(1, 2)))
fourfoldplot(x)
```

## `mosaicplot()`

```{r mosaincplot, echo = FALSE, fig.height = 5, fig.width = 8}
par(mfrow = c(1,2))
mosaicplot(Titanic, color = TRUE)
mosaicplot(~ FINS_ESTRATOVIVIENDAENERGIA + FINS_NIVELEDUCATIVOMADRE,
           data = SB11_20142, color = 2:3, las = 1)
```

## `stars()`

```{r stars-a, echo=FALSE, fig.height=5, fig.width=8}
par(mfrow = c(1,2), mar = rep(0, 4))
stars(mtcars[, 1:7], locations = c(0, 0), radius = FALSE,
      key.loc = c(0, 0), lty = 2)

stars(mtcars[, 1:7], key.loc = c(14, 2))
```

## `stars()`

```{r stars-b, echo=FALSE, fig.height=5, fig.width=8}
palette(rainbow(12, s = 1, v = 0.75))
stars(mtcars[, 1:7], len = 0.6, key.loc = c(1.5, 0),
      draw.segments = TRUE,
      frame.plot = TRUE, nrow = 4, cex = .5)
```